### ISSUE TITLE
Post-processing of merged bean definition failed

### ISSUE THREAD

**Issue by sergefedorow** [ONLYOFFICE/onlyoffice-alfresco#6] opened 2019-04-17 11:32 UTC
Hi 
Repo module don't start on community Alfresco 6 (java 11.0.1). It gives error and alfresco container didn't start.

_2019-04-17 14:08:28,470  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webscript.onlyoffice.callback.post' defined in URL [jar:file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/onlyoffice-integration-platform-jar-2.0.0.jar!/com/parashift/onlyoffice/CallBack.class]: Post-processing of merged bean definition failed; nested exception is java.lang.NoSuchMethodError: javax.annotation.Resource.lookup()Ljava/lang/String;_

I try to build maven project on java 8 and java 11. Results are the same. I try to add javax.annotation/javax.annotation-api and javax.xml.bind/jaxb-api. Didn't help.

Deployment: docker-compose. 
OS Ubuntu 18.04.2 LTS. 
Docker 18.09.5. 
Docker-compose 1.24.0.
Images:
   alfresco/alfresco-content-repository-community:6.1.2-ga (java 11.0.1)
   alfresco/alfresco-share:6.1.0 (java 11.0.2)

**Comment by SmithJohnTaylor** [comment] 2019-04-17 12:11
I have the same issue with Alfresco 6.1.* enterprise using docker-compose. The platform jar is causing the issue, if I remove it from the deployment, Alfresco starts successfully with only the share jar.

**Comment by Eloncase** [comment] 2019-04-19 12:57
Hi. Should be working after https://github.com/ONLYOFFICE/onlyoffice-alfresco/commit/53c1baa3b1d31a474a9a5cda0f5959c831e78a3b
Can you please apply the fix and see if it works for you?

**Comment by SmithJohnTaylor** [comment] 2019-04-22 01:58
I rebuild the jars based on the dev branch and got the same error. see below:

`alfresco_1               | 2019-04-22 01:55:41,386  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
alfresco_1               | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configManager' defined in URL [jar:file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/onlyoffice-integration-platform-jar-2.0.1.jar!/com/parashift/onlyoffice/ConfigManager.class]: Post-processing of merged bean definition failed; nested exception is java.lang.NoSuchMethodError: javax.annotation.Resource.lookup()Ljava/lang/String;
alfresco_1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
alfresco_1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
alfresco_1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
alfresco_1               | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
alfresco_1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
alfresco_1               | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
alfresco_1               | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
alfresco_1               | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
alfresco_1               | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
alfresco_1               | 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
alfresco_1               | 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
alfresco_1               | 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
alfresco_1               | 	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
alfresco_1               | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4792)
alfresco_1               | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
alfresco_1               | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
alfresco_1               | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
alfresco_1               | 	at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
alfresco_1               | 	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:150)
alfresco_1               | 	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:140)
alfresco_1               | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1               | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
alfresco_1               | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
alfresco_1               | 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140)
alfresco_1               | 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
alfresco_1               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
alfresco_1               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
alfresco_1               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
alfresco_1               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
alfresco_1               | 	at java.base/java.lang.Thread.run(Thread.java:834)
alfresco_1               | Caused by: java.lang.NoSuchMethodError: javax.annotation.Resource.lookup()Ljava/lang/String;
alfresco_1               | 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.<init>(CommonAnnotationBeanPostProcessor.java:621)
alfresco_1               | 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.lambda$buildResourceMetadata$0(CommonAnnotationBeanPostProcessor.java:383)
alfresco_1               | 	at org.springframework.util.ReflectionUtils.doWithLocalFields(ReflectionUtils.java:713)
alfresco_1               | 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.buildResourceMetadata(CommonAnnotationBeanPostProcessor.java:365)
alfresco_1               | 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.findResourceMetadata(CommonAnnotationBeanPostProcessor.java:350)
alfresco_1               | 	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:298)
alfresco_1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1044)
alfresco_1               | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:550)
alfresco_1               | 	... 29 more`

**Comment by SmithJohnTaylor** [comment] 2019-04-22 15:09
the MVN build shows issues with the new dependencies:

`[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ 

[WARNING] The POM for com.sun.xml.bind:jaxb-impl:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.sun.xml.bind:jaxb-impl:2.2.11
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ 

[WARNING] The POM for com.sun.xml.bind:jaxb-xjc:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.sun.xml.bind:jaxb-xjc:2.2.11
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ 
`

**Comment by Eloncase** [comment] 2019-04-23 15:52
completely got rid of javax.annotations dependency https://github.com/ONLYOFFICE/onlyoffice-alfresco/commit/db8913cdfd9e7037e2e5787ec0ff606744c0777a

**Comment by SmithJohnTaylor** [comment] 2019-04-23 19:23
Success! Thank you. FWIW I'm using Java 11.

**Closed** 2019-06-26 11:15 UTC
