### ISSUE TITLE
versioning and checkin behavior

### ISSUE THREAD

**Issue by hi-ko** [ONLYOFFICE/onlyoffice-alfresco#184] opened 2023-06-28 13:41 UTC
When openening an office document from alfresco in onlyoffice the document is getting checked out and once the last user closes the editor in onlyoffice the module checks the modified document in without comment creating a new major version:
https://github.com/ONLYOFFICE/onlyoffice-alfresco/blob/7111204007efe94ce4292f8dd84e02a8cab48863/repo/src/main/java/com/parashift/onlyoffice/scripts/CallBack.java#L215

This behavior is hard coded. From the end user perspective the user should be able to decide if it's a major or minor change resulting in a version digit increase before or after the dot in the version number and enter a version comment. Since this change may require changes in the onlyoffice viewer (listening on window close event) we should at least make the versioning behavior configurable from the alfresco-global.propteries and/or from the admin console.

**Comment by GeorgeONLYOFFICE** [comment] 2023-06-28 15:02
The issue is being taken care of by the Support team in ticket 42506 and is related to a force save mechanism usage for minor versions to appear in Alfresco.

**Comment by hi-ko** [comment] 2023-06-28 15:51
OK to explain the existing behavior:
* the onlyoffice-alfresco module creates always a major version on close
* when enabling "Force save" the save button in onlyoffice gets active and creates an *additional minor* version on click but on close a new major version will be created anyway.

As I understand it, this is not the expected behavior for versioning in alfresco and I would vote to extend the onlyoffice versioning on close (callback) so that it can be changed to `MINOR` by configuration.

**Comment by aleksandrfedorov97** [comment] 2024-04-26 09:08
[hi-ko](https://github.com/hi-ko), we added the setting "After closing the editor, save the document as a minor version." in [v.7.0.0](https://github.com/ONLYOFFICE/onlyoffice-alfresco/releases/tag/v7.0.0)

**Closed by aleksandrfedorov97** 2024-04-26 09:08 UTC
Labels: enhancement
